name: operation-battleship-frontend
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: CarawayLabs/OperationBattleshipFrontend
  name: operation-battleship-frontend